init: Set up the encrypted reboot vault on startup
Unlock the encrypted reboot vault after the encrypted stateful
partition has been mounted. If the encryption key is available,
then the contents from the last boot can be unlocked. This allows
us to get logs when the encrypted stateful partition is not
available. If an existing reboot vault isn't available (due to
power loss/reboot), attempt to create a new vault.

BUG=chromium:1025044
TEST=none

Change-Id: I3b1c15401373411f38792d07d11534ce3902aea5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/2093378
Tested-by: Sarthak Kukreti <sarthakkukreti@chromium.org>
Commit-Queue: Sarthak Kukreti <sarthakkukreti@chromium.org>
Reviewed-by: Gwendal Grignou <gwendal@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>

diff --git a/init/chromeos_startup b/init/chromeos_startup
--- a/init/chromeos_startup
+++ b/init/chromeos_startup
@@ -457,6 +457,13 @@ mount --make-shared /home/root
 do_mount_var_and_home_chronos || cleanup_mounts "var and home"
 remember_mount "${ENCRYPTED_STATEFUL_MNT}"
 
+# Setup the encrypted reboot vault once the encrypted stateful partition
+# is available. If unlocking the encrypted reboot vault failed (due to power
+# loss/reboot/invalid vault), attempt to recreate the encrypted reboot vault.
+if ! encrypted-reboot-vault --action=unlock; then
+  encrypted-reboot-vault --action=create
+fi
+
 force_clean_file_attrs /var
 force_clean_file_attrs /home/chronos
 
